name: Testing

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - uses: paambaati/codeclimate-action@v2.7.5
        if: ${{ matrix.node == '14' }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
      - run: npm run coverage
        if: ${{ matrix.node != '14' }}
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test-browser 
